### PR TITLE
remove flow-HTML-components dependency

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/7)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0soImRM2e9twNaVhtg:ble5xy9) (no related file):*
The commit message is misleading.
It doesn't remove imports. It removes dependency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0soahGWW7B2h_XqLZx:b-vnoifv) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The commit message is misleading.
It doesn't remove imports. It removes dependency.
</blockquote></details>

yes.. correct...  how should i correct it...?? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0spu3rfdjsktqONIkV:b-9b5an9) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

yes.. correct...  how should i correct it...?? 
</blockquote></details>

ah.. got it correct now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0srecYBQUpXCdr-4K6:b-95p6b) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

ah.. got it correct now.
</blockquote></details>

How ?
You should correct PR message. It's the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0ss-p0eGm-QKH1QW1k:b-6a4w6i) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

How ?
You should correct PR message. It's the same.
</blockquote></details>

I did it according to https://help.github.com/articles/changing-a-commit-message/ this one.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0ssS0LKFOUzjE5EQZJ:b-omyg7e) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

I did it according to https://help.github.com/articles/changing-a-commit-message/ this one.. 
</blockquote></details>

and PR title is changed too.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7#-L0soImRM2e9twNaVhtf:-L0t-yj39Z-IZ3SNUhT_:b96ac3i) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and PR title is changed too.. 
</blockquote></details>

Your commit message will be derived from the PR title.
One PR may contain several commits.
Their commit messages are accumulated by default into one when you squash and merge.
But they will be appended there in the end.
The main an important commit message is the message in the last "squash and merge".
You may edit it when you do it (via the github, not reviewable).
But you can't amend it via the mentioned link just because you amend some of your "interim" commits not the final "merge" commit.

So it's always better to keep appropriate PR title.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/7)*

**Pull request merged**
