### PR TITLE
Notification is now removed from the DOM when closed

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
The Notification is removed when it is automatically added to the DOM during the open() call. If the user decides to add it to the DOM by himself, then the Notification is not removed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/28)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 167 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/28#-L5wql6kwo_Ruml6HsNT:-L5wql6kwo_Ruml6HsNU:b-d5dh34) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/main/java/com/vaadin/flow/component/notification/Notification.java#L167)):*
> addOpenedChangeListener(event -> {
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>             if (autoAddedToTheUi && !isOpened()) {
>                 getElement().removeFromParent();
>                 autoAddedToTheUi = false;
>             }
>         });
</details>

What if I add the `Notification` explicitly to some component ?

So instead of :
```
Notification notification = new Notification();
notification.open();
```

I do :
```
Div div = ...
Notification notification = new Notification();

div.add(notification);
notification.open();
```

May be we don't want to remove it in this case implicitly and it's the developer responsibility to remove it? Not sure.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 205 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/28#-L5wr9jIjo464Wc1uiPc:-L5wr9jIjo464Wc1uiPd:b-thxdw3) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L205)):*
> private void createNotificationOutsideUi() {

Should be test when notification is added explicitly to some component depending on decision whether we want or not to remove `Notification` if it's added explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/28)*

**Comment by gilberto-torrezan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 167 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28#-L5wql6kwo_Ruml6HsNT:-L5x6PjW8CNw_2gHSuho:b-z2ffye) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/main/java/com/vaadin/flow/component/notification/Notification.java#L167)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> addOpenedChangeListener(event -> {
>             if (autoAddedToTheUi && !isOpened()) {
>                 getElement().removeFromParent();
>                 autoAddedToTheUi = false;
>             }
>         });

What if I add the `Notification` explicitly to some component ?

So instead of :
```
Notification notification = new Notification();
notification.open();
```

I do :
```
Div div = ...
Notification notification = new Notification();

div.add(notification);
notification.open();
```

May be we don't want to remove it in this case implicitly and it's the developer responsibility to remove it? Not sure.
</blockquote></details>

That's exactly the purpose of the `autoAddedToTheUi` flag. It is only set when the Notification is auto inserted in the DOM by the `open()` method.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 205 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28#-L5wr9jIjo464Wc1uiPc:-L5x6fFi8tgeaaTSnu2_:b-fsam5w) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L205)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private void createNotificationOutsideUi() {

Should be test when notification is added explicitly to some component depending on decision whether we want or not to remove `Notification` if it's added explicitly.
</blockquote></details>

All other tests already add the `Notification` directly to the DOM. I can add some checks to make sure the component is still there after it is closed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 167 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28#-L5wql6kwo_Ruml6HsNT:-L5xAmMR1di99_37oy0O:bl6dr6w) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/main/java/com/vaadin/flow/component/notification/Notification.java#L167)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That's exactly the purpose of the `autoAddedToTheUi` flag. It is only set when the Notification is auto inserted in the DOM by the `open()` method.
</blockquote></details>

The question is : should it be always removed on `close()` ?
Or auto removal should work only on auto insertion....

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 205 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28#-L5wr9jIjo464Wc1uiPc:-L5xB0n78fUGtDo2j3Hp:b-x12kct) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/c879fd4be60169d0258d004c5ba5660a98ca5ee7/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L205)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

All other tests already add the `Notification` directly to the DOM. I can add some checks to make sure the component is still there after it is closed.
</blockquote></details>

No need.
The question is should it be auto removed always on close() (if possible)....

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification-flow/28)*

**Pull request merged**
