### PR TITLE
Add Notification component support

### PR DESCRIPTION
**Pull request by ZheSun88**
add needed dependency to pom;
add IT tests;
add unit tests.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/6)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqAbL8_ISnYnlyFdK:-L0nqAbL8_ISnYnlyFdL:b-29k0rn) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L61)):*
> getElement().getNode().runWhenAttached(

Most likely it should use `StateTree::beforeClientResponse` inside.
Otherwise the code will be executed even if the element is detached (after attach and before sending the request to the client).

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nq-WV9GL3rVdeXclW:-L0nq-WV9GL3rVdeXclX:bvnafv6) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L62)):*
> UI.getCurrent(

an `ui`is available as an argument here exactly to avoid using `UI.getCurrent()`.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqs4Ud7iwMoJXe5-F:-L0nqs4Ud7iwMoJXe5-G:bnhgy9n) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L83)):*
> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqyWe3FOnZU_9vz5K:-L0nqyWe3FOnZU_9vz5L:br11bw5) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L97)):*
> button_off 

Camel Case please.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 105 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqx-8C2XsHUek-hk7:-L0nqx-8C2XsHUek-hk8:bnhgy9n) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L105)):*
> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nr02KbmvFQYaPYvuc:-L0nr02KbmvFQYaPYvud:bnhgy9n) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L127)):*
> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nr56Gdyg2TC-G2elT:-L0nr56Gdyg2TC-G2elU:b2a42qb) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L67)):*
> "true"

May be `Boolean.TRUE.toString()`. Avoid hardcoding whenever possible.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrGQYoSN7UIXg-e9t:-L0nrGQYoSN7UIXg-e9u:b-m3oadg) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L74)):*
> "false"

same here (hardcoding)

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrE6hBfanOlgj32T5:-L0nrE6hBfanOlgj32T6:bo9juxn) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L82)):*
> "true"

same here (hardcoding)

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrKUA740_TLCR5Roj:-L0nrKUA740_TLCR5Rok:b-m3oadg) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L90)):*
> "false"

same here (hardcoding)

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrM4HcFj0RAuiJqsX:-L0nrM4HcFj0RAuiJqsY:bo9juxn) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L98)):*
> "true"

same here (hardcoding)

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrNDEcUsPm2k-UcWg:-L0nrNDEcUsPm2k-UcWh:b-m5jijy) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L106)):*
> "false"


same here (hardcoding)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: 4 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqs4Ud7iwMoJXe5-F:-L0o1AupTAESkBTQwaNj:b8efsp2) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L83)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?
</blockquote></details>

oops. removed

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 97 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqyWe3FOnZU_9vz5K:-L0o1Cd_ep7oFdio0oQZ:b-hff6wv) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L97)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> button_off 

Camel Case please.
</blockquote></details>

renamed

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 105 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqx-8C2XsHUek-hk7:-L0o1EhfGb5-RaBQo5QE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L105)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nr02KbmvFQYaPYvuc:-L0o1Fx-Hl2eRhc05_ZO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPage.java#L127)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> // button1.setId("button1");
>         // button2.setId("button2");
>         // button3.setId("button3");

?
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nr56Gdyg2TC-G2elT:-L0o1HhZxncH5qAmGzLR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L67)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "true"

May be `Boolean.TRUE.toString()`. Avoid hardcoding whenever possible.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrGQYoSN7UIXg-e9t:-L0o1I3H9J_4s-XZphxg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L74)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "false"

same here (hardcoding)
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 82 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrE6hBfanOlgj32T5:-L0o1Ib4GPKGHyjVDxav:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L82)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "true"

same here (hardcoding)
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrKUA740_TLCR5Roj:-L0o1IwLbs3x13jiWyqY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L90)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "false"

same here (hardcoding)
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 98 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrM4HcFj0RAuiJqsX:-L0o1JGWcd0IVVE1E0TN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L98)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "true"

same here (hardcoding)
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nrNDEcUsPm2k-UcWg:-L0o1JeYgQhI0VJUA96l:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/test/java/com/vaadin/flow/component/notification/tests/NotificationTestPageIT.java#L106)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> "false"


same here (hardcoding)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: 4 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqAbL8_ISnYnlyFdK:-L0o1Lw22NE0s2h8R8Y2:b-c1enfo) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L61)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getElement().getNode().runWhenAttached(

Most likely it should use `StateTree::beforeClientResponse` inside.
Otherwise the code will be executed even if the element is detached (after attach and before sending the request to the client).
</blockquote></details>

should i use `StateTree` or `ui` for beforeClientResponse? 

how dose it work like?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: 3 of 7 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nqAbL8_ISnYnlyFdK:-L0o4VoXSZ1u5I6LijOE:b-rsrg) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L61)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

should i use `StateTree` or `ui` for beforeClientResponse? 

how dose it work like?
</blockquote></details>

should it  look like this???

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nq-WV9GL3rVdeXclW:-L0o4vGz20eGZ6W6UbY-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L62)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> UI.getCurrent(

an `ui`is available as an argument here exactly to avoid using `UI.getCurrent()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nq-WV9GL3rVdeXclW:-L0oJzmkHq00fCSTQ_Fi:bb77ufg) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L62)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 61 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0oKKOZlABHVZ5qfQ4S:-L0oKKOZlABHVZ5qfQ4T:b-1tl4oz) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/183a3c584bd82a06ceea122114188e61d8d7937c/src/main/java/com/vaadin/flow/component/notification/Notification.java#L61)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>             String appId = ui.getSession().getService()
>                             .getMainDivId(ui.getSession(),
>                             VaadinRequest.getCurrent());
>             appId = appId.substring(0, appId.indexOf("-"));
</details>
>  
>             int nodeId = container.getNode().getId();
>  
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>             String template = "<template><flow-component-renderer appid="
>                     + appId + " nodeid=" + nodeId
>                     + "></flow-component-renderer></template>";
>             getElement().setProperty("innerHTML", template);
>         }
</details>


Please extract this lambda as a method reference.

It's too long for lambda. Bad readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 61 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0oKKOZlABHVZ5qfQ4S:-L0rkq77a_L2s0ZCfvZ3:b3mze0) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/183a3c584bd82a06ceea122114188e61d8d7937c/src/main/java/com/vaadin/flow/component/notification/Notification.java#L61)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>             String appId = ui.getSession().getService()
>                             .getMainDivId(ui.getSession(),
>                             VaadinRequest.getCurrent());
>             appId = appId.substring(0, appId.indexOf("-"));
>  
>             int nodeId = container.getNode().getId();
>  
>             String template = "<template><flow-component-renderer appid="
>                     + appId + " nodeid=" + nodeId
>                     + "></flow-component-renderer></template>";
>             getElement().setProperty("innerHTML", template);
>         }


Please extract this lambda as a method reference.

It's too long for lambda. Bad readability.
</blockquote></details>

Thanks, I took the whole template adding lambda out. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 236 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0roiTbNPd2uLbx-rqW:-L0roiTbNPd2uLbx-rqX:bq8kgxx) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/08811a18a806e547acbd709149e9038720c2f636/src/main/java/com/vaadin/flow/component/notification/Notification.java#L236)):*
> return () -> {

No need to return lambda here.
You just moved the lambda from one place to another.
This method should not return anything.
It should just do what the `Runnable` does.

Use _method reference_ where you call this method.
`this::attachComponentTamplete` instead of `attachComponentTamplete(.......)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 236 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0roiTbNPd2uLbx-rqW:-L0s2eynWQgYRln6N4mM:b-ddkx24) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/08811a18a806e547acbd709149e9038720c2f636/src/main/java/com/vaadin/flow/component/notification/Notification.java#L236)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> return () -> {

No need to return lambda here.
You just moved the lambda from one place to another.
This method should not return anything.
It should just do what the `Runnable` does.

Use _method reference_ where you call this method.
`this::attachComponentTamplete` instead of `attachComponentTamplete(.......)`.
</blockquote></details>

umm.. is this correct? 
because for this lambda, there is no object (as it is `() -> {method}`) for the method reference.. Can i ask for some more detailed instructions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 236 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0roiTbNPd2uLbx-rqW:-L0sA1xfWjJ6Xz5FeSiz:b-2hbz2k) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/08811a18a806e547acbd709149e9038720c2f636/src/main/java/com/vaadin/flow/component/notification/Notification.java#L236)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

umm.. is this correct? 
because for this lambda, there is no object (as it is `() -> {method}`) for the method reference.. Can i ask for some more detailed instructions?
</blockquote></details>

or we could do it in this way..if it is okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 236 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0roiTbNPd2uLbx-rqW:-L0sDptV1s-459kBVIvA:bz1try6) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/08811a18a806e547acbd709149e9038720c2f636/src/main/java/com/vaadin/flow/component/notification/Notification.java#L236)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

or we could do it in this way..if it is okay?
</blockquote></details>

OK, that requires an `UI`  instance. 

`this::attachComponentTamplete` cannot be used.
My bad, sorry.

But still.

Change the call in the CTOR from 

```
getElement().getNode()
                .runWhenAttached(ui -> ui.beforeClientResponse(this, attachComponentTamplete(ui)));
```

to 

```
getElement().getNode()
                .runWhenAttached(ui -> ui.beforeClientResponse(this, ()->attachComponentTamplete(ui)));
```


And the method `attachComponentTamplete` should not return any value and should not have `Runnable` as a lambda inside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 236 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0roiTbNPd2uLbx-rqW:-L0sGXf6SI7gtczS73CP:b-35c1lb) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/08811a18a806e547acbd709149e9038720c2f636/src/main/java/com/vaadin/flow/component/notification/Notification.java#L236)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

OK, that requires an `UI`  instance. 

`this::attachComponentTamplete` cannot be used.
My bad, sorry.

But still.

Change the call in the CTOR from 

```
getElement().getNode()
                .runWhenAttached(ui -> ui.beforeClientResponse(this, attachComponentTamplete(ui)));
```

to 

```
getElement().getNode()
                .runWhenAttached(ui -> ui.beforeClientResponse(this, ()->attachComponentTamplete(ui)));
```


And the method `attachComponentTamplete` should not return any value and should not have `Runnable` as a lambda inside.
</blockquote></details>

okay, got it done. Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/notification/Notification.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6#-L0nq-WV9GL3rVdeXclW:-L0sLK4gqYA6V2ftoMse:blz7ckt) ([raw file](https://github.com/vaadin/vaadin-notification-flow/blob/38d20a46de73d7ce3fe0218bc57f17a8d47fc276/src/main/java/com/vaadin/flow/component/notification/Notification.java#L62)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

is this another blocker? T.T

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/6)*

**Pull request merged**
