### PR TITLE
Add static Convenience method for notification

### PR DESCRIPTION
**Pull request by ZheSun88**
add demo;
add unit test;
add IT test.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification-flow/11)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/11)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/11)*

**Comment by caalador** [comment]
Is this needed as it will change and horizontal and vertical positioning will not be used anymore.

**Comment by ZheSun88** [comment]
according the original requirement, `Including using the component instance, there is a static convenience method for showing a notification by giving just text, position and duration of notification, and the notification is automatically added to the current UI`. 

this should be merged before change the position setting... . so we can merge this one in and i will resolve the conflict immediately..

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/11#-:-L1ujbGnRiYvozuHD8Fn:boz6g9j)*

**Comment by ZheSun88** [comment]
@caalador conflict resolved. Waaayaaaa

**Comment by caalador** [comment]
Reviewed 1 of 2 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification-flow/11)*

**Pull request merged**
